Added precommit hook
Girl-Code-It/Opportunity-Calendar-Backend pull request #67
Opened 2021-04-24 13:43 UTC by Samridhi-98

# Description

Added pre-commit hook  `.pre-commit-config.yaml`

Fixes #62

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2021-04-24 13:44 UTC, Samridhi-98 commented
@Manvityagi  Please review my PR.

2021-04-24 14:24 UTC, abdus commented
hey @Samridhi-98, did you test these changes locally before making a Pull Request? from what I can see, you have installed `husky@6` for this project. But the way you have implemented it .. works with `husky@4`. so, the pre-commit hooks never actually get triggered. 

following are the changes I want you to make:
1. remove `.pre-commit-config.yaml. this is required only if you are using [pre-commit](https://pre-commit.com/) framework
2. migrate the implementation to husky@6. resources: [installation](https://typicode.github.io/husky/#/?id=install)  &middot; [migration](https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v6)
3. update readme with relevant information (for example, if there's any additional commands user required to run while setting up the project locally)

Let me know if you need any help. And please test your code locally before making PRs.

2021-04-24 14:31 UTC, Samridhi-98 commented
> hey @Samridhi-98, did you test these changes locally before making a Pull Request? from what I can see, you have installed `husky@6` for this project. But the way you have implemented it .. works with `husky@4`. so, the pre-commit hooks never actually get triggered.
> 
> following are the changes I want you to make:
> 
> 1. remove `.pre-commit-config.yaml. this is required only if you are using [pre-commit](https://pre-commit.com/) framework
> 2. migrate the implementation to husky@6. resources: [installation](https://typicode.github.io/husky/#/?id=install)  · [migration](https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v6)
> 3. update readme with relevant information (for example, if there's any additional commands user required to run while setting up the project locally)
> 
> Let me know if you need any help. And please test your code locally before making PRs.

Okay, will update as you suggested.

2021-04-24 16:46 UTC, Samridhi-98 commented
@abdus  Please review I have updated as you suggested and also tested my code locally.

**Screenshot**

![ss](https://user-images.githubusercontent.com/54466041/115966313-9ae82480-a54a-11eb-8dfb-0a5ecbceb3eb.JPG)

2021-04-25 07:14 UTC, abdus requested changes
The changes you have made aren't working as expected. Files that were changed since the last commit, should be formatted automatically using prettier before commit. 

Also, by "test your code locally", I meant to say that whatever code you have changed, is working as expected. For example, here you are working on formatting code with the pre-commit hook. check that whether the changed files were formatted or not.

I wrote a [how-to on writing a pre-commit hook using husky@6](https://log.abdus.net/#Sun,%2025%20Apr%202021%2000:00:00%20GMT). please check it out and see if this could be of any help.

2021-04-25 07:14 UTC, abdus commented on README.md
> +
`pre-commit` hook should run automatically before committing the changes.

2021-04-25 07:14 UTC, abdus commented on package.json
> +    }
you need to install `prettier` and `pretty-quick` as well.

2021-04-25 07:45 UTC, Samridhi-98 commented
@abdus  Please review. Also while running this `npx husky add .husky/pre-commit './node_modules/.bin/pretty-quick --staged'` got an error so I created the file `npx husky add .husky/pre-commit` first and then added this  `'./node_modules/.bin/pretty-quick --staged'` manually and its working, please let me know if I did anything wrong.

**Screenshot**
![github](https://user-images.githubusercontent.com/54466041/115985076-bf361680-a5c7-11eb-8a8f-5defdf0f3df4.JPG)

2021-04-25 11:04 UTC, abdus approved these changes

2021-04-25 11:04 UTC, merged

2021-04-25 11:14 UTC, Samridhi-98 commented
@Manvityagi  please add the appropriate label