DELETE Endpoint added
Girl-Code-It/Opportunity-Calendar-Backend pull request #79
Opened 2021-04-27 11:17 UTC by Vishal1003

# Description

I have added the relevant changes (delete method for the opportunities). Kindly review my changes!

Fixes #74

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

RESPONSE IMAGE -
![image](https://user-images.githubusercontent.com/44357051/116232790-34e0e480-a778-11eb-9d0f-82dcc9c61b50.png)

2021-04-28 14:14 UTC, Manvityagi requested changes
@Vishal1003 Respective Tests for the API should also be added.

2021-05-01 06:57 UTC, Manvityagi commented
Any updates @Vishal1003 ?

2021-05-01 07:51 UTC, Vishal1003 commented
@Manvityagi Sorry for the delay. I have done my task but the getOpportunity tests are failing (don't know why)  after I merged with the upstream branch (and I believe there is a separate issue for resolving this). 

Kindly review my changes. Thank you!

2021-05-01 08:47 UTC, Manvityagi commented
> @Manvityagi @abdus Sorry for the delay. I have done my task but the getOpportunity tests are failing (don't know why) after I merged with the upstream branch (and I believe there is a separate issue for resolving this).
> 
> Kindly review my changes. Thank you!

Yeah, you are right. We are figuring what's wrong with it.

2021-05-01 10:25 UTC, Manvityagi commented
@Vishal1003  Pull the latest code, the issue has been fixed

2021-05-01 10:56 UTC, Manvityagi commented
Have you entered the right credentials in `.env` , the build fails, seems like a connection to DB could not be established.

2021-05-01 11:00 UTC, Vishal1003 commented
> Have you entered the right credentials in `.env`? The build fails, seems like a connection to DB could not be established.

I;m cross checking the tests.. On my pc it is running fine.

2021-05-01 11:44 UTC, Manvityagi commented
> > Have you entered the right credentials in `.env`? The build fails, seems like a connection to DB could not be established.
> 
> @Manvityagi Yes i entered the correct credentials.. I don't know why the build is failing.. (the tests are running fine on my pc).

Take the pull once more, it should work now

2021-05-01 11:59 UTC, Vishal1003 commented
> > > Have you entered the right credentials in `.env`? The build fails, seems like a connection to DB could not be established.
> > 
> > 
> > @Manvityagi Yes i entered the correct credentials.. I don't know why the build is failing.. (the tests are running fine on my pc).
> 
> Take the pull once more, it should work now

Done! Kindly review my changes (for issue #74 ) Thank you

2021-05-01 12:59 UTC, Manvityagi requested changes
Please do the changes as mentioned in comments

2021-05-01 12:59 UTC, Manvityagi commented on routes/opportunity.js
> + * @openapi1
There is a extra `1` after @openapi, due to which this API doesn't show up in Swagger UI at http://localhost:3030/playground

2021-05-01 12:59 UTC, Manvityagi commented on routes/opportunity.js
> + *      - id: type
``` 
*     parameters:
 *      - name: opportunity_id
 *        in: path
 *        schema:
 *          type: string
 *        description: mongo_id of a Particular opportunity
 *
 ```

It should be like this

2021-05-01 12:59 UTC, Manvityagi commented on routes/opportunity.js
> +router.delete('/:id', (req, res) => {
change this name from `'/:id'` to `/:opportunity_id`

2021-05-01 12:59 UTC, Manvityagi commented on routes/opportunity.js
> +router.delete('/:id', (req, res) => {
Here and everywhere else

2021-05-02 06:26 UTC, Vishal1003 commented
> Please do the changes as mentioned in comments

@Manvityagi I have made all the necessary changes.

2021-05-02 07:31 UTC, Manvityagi approved these changes
Awesome @Vishal1003. Merging

2021-05-02 07:32 UTC, merged